
apiVersion: apps/v1
kind: Deployment
metadata:
  name: username-check-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: username-check-api
  template:
    metadata:
      labels:
        app: username-check-api
    spec:
      containers:
      - name: username-check-api
        image: your-dockerhub-username/username-check-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: username-check-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: username-check-api
